### ISSUE TITLE
New color function with all RGB colors

### ISSUE THREAD

**Issue by Newan** [joaquincasares/python-wifi-leds#4]
Hello,

it is possible to include a function, like this color funktion:
https://github.com/jpsilvashy/limitless-led

He can work with all RGB / HTML colors, but in ruby not in python

best regards

**Comment by joaquincasares** [comment]
Hello @Newan ,

Sorry for the late response, but I still have not purchased these new lights. When/if I get these new lights, I'll definitely be updating this repo. I do, however, accept pull requests in case you want to implement these changes. :)

**Comment by Seraf** [comment]
It seems also there was lot of changes with RGB+W lights, and the new v4 controller.
I just changed my old lights/controller to the new one.

The old code don't work, I will check if it is possible to reuse this code by adjusting some parameters/codes

UPDATE: Said nothing all works correctly. The port is now 8899.

**Comment by joaquincasares** [comment]
Hello, closing this out since I got a community pull request for RGB+W lights:
https://github.com/joaquincasares/python-wifi-leds/pull/6

Hope it works for you!
